---
- name: Ensure syslog repository is configured
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng335/repo/fedora-{{ ansible_distribution_major_version }}/czanik-syslog-ng335-fedora-{{ ansible_distribution_major_version }}.repo
    dest: /etc/yum.repos.d/czanik-syslog-ng335-fedora-{{ ansible_distribution_major_version }}.repo
